Repository gdsc-konkuk/24-25-proj-U2E-Server, pull requests merged in 2025-05, with the labels that each got.

#10 [FEAT] 최신 뉴스 5개 반환 api 구현
  U2E/build.gradle
  U2E/src/main/java/Konkuk/U2E/domain/news/controller/NewsController.java
  U2E/src/main/java/Konkuk/U2E/domain/news/dto/response/GetLatelyNewsResponse.java
  U2E/src/main/java/Konkuk/U2E/domain/news/dto/response/LatelyNews.java
  U2E/src/main/java/Konkuk/U2E/domain/news/repository/ClimateRepository.java
  U2E/src/main/java/Konkuk/U2E/domain/news/repository/NewsPinRepository.java
  U2E/src/main/java/Konkuk/U2E/domain/news/repository/NewsRepository.java
  U2E/src/main/java/Konkuk/U2E/domain/news/service/NewsLatelyService.java
Labels: ✨feat

#14 [chore] cors 에러 핸들링
  U2E/src/main/java/Konkuk/U2E/global/config/WebConfig.java
Labels: 📜chore

#19 [FEAT] 로그인 API 개발
  U2E/build.gradle
  U2E/src/main/java/Konkuk/U2E/domain/user/controller/UserController.java
  U2E/src/main/java/Konkuk/U2E/domain/user/domain/User.java
  U2E/src/main/java/Konkuk/U2E/domain/user/dto/request/PostUserLoginRequest.java
  U2E/src/main/java/Konkuk/U2E/domain/user/dto/response/PostUserLoginResponse.java
  U2E/src/main/java/Konkuk/U2E/domain/user/exception/DuplicateUserException.java
  U2E/src/main/java/Konkuk/U2E/domain/user/exception/InvalidAccessTokenException.java
  U2E/src/main/java/Konkuk/U2E/domain/user/exception/handler/UserControllerAdvice.java
  U2E/src/main/java/Konkuk/U2E/domain/user/repository/UserRepository.java
  U2E/src/main/java/Konkuk/U2E/domain/user/service/JwtUtil.java
  U2E/src/main/java/Konkuk/U2E/domain/user/service/UserService.java
  U2E/src/main/java/Konkuk/U2E/global/annotation/LoginUser.java
  U2E/src/main/java/Konkuk/U2E/global/auth/interceptor/AuthInterceptor.java
  U2E/src/main/java/Konkuk/U2E/global/auth/resolver/LoginUserArgumentResolver.java
  U2E/src/main/java/Konkuk/U2E/global/config/WebConfig.java
  U2E/src/main/java/Konkuk/U2E/global/config/initData/CommentUserInitializer.java
  U2E/src/main/java/Konkuk/U2E/global/response/status/BaseExceptionResponseStatus.java
  U2E/src/main/resources/application.yml
Labels: ✨feat

#21 [FEAT] 댓글 조회 API 개발
  U2E/src/main/java/Konkuk/U2E/domain/comment/controller/CommentController.java
  U2E/src/main/java/Konkuk/U2E/domain/comment/dto/response/CommentInfo.java
  U2E/src/main/java/Konkuk/U2E/domain/comment/dto/response/GetCommentsResponse.java
  U2E/src/main/java/Konkuk/U2E/domain/comment/repository/CommentRepository.java
  U2E/src/main/java/Konkuk/U2E/domain/comment/service/CommentService.java
Labels: ✨feat

#24 [FEAT] Pin 조회 API 개발
  U2E/src/main/java/Konkuk/U2E/domain/news/domain/ClimateProblem.java
  U2E/src/main/java/Konkuk/U2E/domain/news/domain/NewsPin.java
  U2E/src/main/java/Konkuk/U2E/domain/news/exception/handler/NewsControllerAdvice.java
  U2E/src/main/java/Konkuk/U2E/domain/news/repository/ClimateRepository.java
  U2E/src/main/java/Konkuk/U2E/domain/news/repository/NewsPinRepository.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/controller/PinController.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/domain/Pin.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/domain/PinColor.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/dto/response/GetPinListResponse.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/dto/response/PinInfo.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/exception/ClimateNotFoundException.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/exception/InvalidParamException.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/exception/PinNewsNotFoundException.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/exception/handler/PinControllerAdvice.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/repository/PinRepository.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/repository/RegionRepository.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/service/PinInfoService.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/service/PinListService.java
  U2E/src/main/java/Konkuk/U2E/global/config/OpenAPIConfig.java
  U2E/src/main/java/Konkuk/U2E/global/config/WebConfig.java
  U2E/src/main/java/Konkuk/U2E/global/config/initData/RegionPinInitializer.java
  U2E/src/main/java/Konkuk/U2E/global/response/status/BaseExceptionResponseStatus.java
  U2E/src/main/java/Konkuk/U2E/global/util/DateUtil.java
Labels: ✨feat

#27 [chore] 더미데이터 생성 시 오류 수정
  U2E/Dockerfile
  U2E/src/main/java/Konkuk/U2E/global/config/initData/RegionPinInitializer.java
Labels: 🐞bug

#29 [FEAT] 지역으로 핀 검색 api 개발
  U2E/Dockerfile
  U2E/docker-compose.yml
  U2E/src/main/java/Konkuk/U2E/domain/pin/repository/RegionRepository.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/service/PinListService.java
  U2E/src/main/java/Konkuk/U2E/global/config/WebConfig.java
  U2E/src/main/resources/application.yml
Labels: ✨feat

#33 [REFACTOR] 기후로 핀 필터링할때 사용자가 요청한 기후가 아닌 News가 매핑되는 문제 해결
  U2E/src/main/java/Konkuk/U2E/domain/news/repository/ClimateRepository.java
  U2E/src/main/java/Konkuk/U2E/domain/pin/service/PinListService.java
Labels: 🐞bug, ♻️refactor, 🛠️fix
